openapi: 3.0.0

info:
  title: Transactions api agent bank
  description: The second part of the agent bank project :Transactions 
  version: 1.0.0
  contact:
    name: Filali kenza
    email: kenza.filali.rahal@gmail.com

servers:
  - url: http://localhost:3001
    description: HTTP server agent bank


paths:
   /users/{userId}/transactions:
    get:
      tags:
      - user transactions
      description: get all the transactions of the current month
      summary: get the transactions of a user 
      parameters:
       - name: userId
         in: path
         description: ID of the user
         required: true
         schema:
          type: integer
       - name: Authorization
         in: header
         description: Attach Bearer JWT token
         required: true
         schema:
          type: string
       - name: month
         in: query
         description: The month of transactions
         required: false
         schema:
          type: string 
       - name: year
         in: query
         description: The year of transactions
         required: false
         schema:
          type: string 
           
      security:
       - bearerAuth: []
      responses:
        '200':
          description: Account transactions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  table:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        date:
                          type: string
                          format: date
                        description:
                          type: string
                        Amount:
                          type: integer
                        balance:
                          type: integer
        '400':
         description: Bad request. #bad formatted user id 
        '401': 
          description:  unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                  code:
                   type: integer
                  message:
                   type: string
                  date:
                   type: string
                   format: date
        '404':
         description: user id not found
        '500':
          description: Internal Server Error
         
   /transactions/{transactionId}:  
    get:
     tags:
      - user transactions
     description: Details of a single transaction 
     summary: get the details of a single transaction using its id 
     
     parameters:
     - name: transactionId
       in: path
       description: ID of the the transaction
       required: true
       schema:
         type: integer
     - name: Authorization
       in: header
       description: Attach Bearer JWT token
       schema:
         type: string
       required: true
    
     responses:
        '200':
          description: Transaction's info  retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  date:
                   type: string
                   format: date
                  description:
                   type: string
                  Amount:
                   type: integer
                  Balance:
                   type: integer
                  Type:
                   type: string
                  Category:
                   type: string
                  Note:
                   type: string
        
        '400':
          description: Bad request :the format of transaction id is not allowed (must be an integer )
        '404':
          description: resource not found id of transaction not found
        '401':
          description:  unauthorized
        '500':
          description: Internal Server Error
     security:
        - bearerAuth: []
    #edit transactions infos
    #put will allow us to create modify or delete an information of one transaction 
   /transactions/{transactionId}/:
    put:
      tags: 
      - update transactions infos
      description: Update an information of a single transaction
      summary: Update, delete or add an information on a single transaction 
      
      parameters:
      - name: transactionId
        in: path
        description: the ID of the transaction
        required: true
        schema:
         type: integer
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        schema:
         type: string
        required: true
    
        #to treat all manipulation add delete modify we can use put method 
        #with request body that contains the elements of a transaction
        #that we might update  
        #the request body will not be included in the url 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Category:
                  description: The transaction category
                  type: string
                Note:
                  description: A note on the transaction
                  type: string
                TransactionDescription:
                  description: The transaction's description field
                  type: string
                   
          
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Transaction information updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  date:
                   type: string
                   format: date
                  description:
                   type: string
                  Amount:
                   type: integer
                  Balance:
                   type: integer
                  Type:
                   type: string
                  Category:
                   type: string
                  Note:
                   type: string
       
        '400':
          description: Bad request.  transaction ID must be an integer and bigger than 0 / bad information format category , note ,Transaction description 
        '401':
          description:  user unauthorized to make such a modification 
        '404':
          description:  transaction ID /  information  not found ,note id not found 
        '500':
          description: Internal Server Error
   

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      